- name: Copy nginx requirements files
  ansible.builtin.copy:
    src: .
    dest: "{{ project_dir }}/requirements/nginx"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'