- name: Copy wordpress requirements files
  ansible.builtin.copy:
    src: .
    dest: "{{ project_dir }}/requirements/wordpress"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'